const INVALID_DATA_ERROR = 400;

const NOT_FOUND_ERROR = 404;

const DEFAULT_ERROR = 500;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;

module.exports = {
  INVALID_DATA_ERROR,
  NOT_FOUND_ERROR,
  DEFAULT_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
};
